name: My CI/CD

on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        continue-on-error: true
        run: ruff check tests

  integration:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB_AUTH: ${{ secrets.POSTGRES_DB_AUTH }}
      POSTGRES_DB_UNIVERSITY: ${{ secrets.POSTGRES_DB_UNIVERSITY }}
      AUTH_SERVICE_INTERNAL_URL: ${{ secrets.AUTH_SERVICE_INTERNAL_URL }}
      AUTH_SERVICE_API_URL: ${{ secrets.AUTH_SERVICE_API_URL }}
      UNIVERSITY_SERVICE_INTERNAL_URL: ${{ secrets.UNIVERSITY_SERVICE_INTERNAL_URL }}
      UNIVERSITY_SERVICE_API_URL: ${{ secrets.UNIVERSITY_SERVICE_API_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          docker compose version || (sudo curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose)

      - name: Start docker compose stack
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Wait for postgres-auth
        uses: stringbean/docker-healthcheck-action@v1
        with:
          container: postgres-auth
          wait-time: 45
          require-healthy: true

      - name: Wait for postgres-university
        uses: stringbean/docker-healthcheck-action@v1
        with:
          container: postgres-university
          wait-time: 45
          require-healthy: true

      - name: Run integration tests
        continue-on-error: true
        run: |
          docker run --rm \
            --network host \
            -v $(pwd):/workspace \
            -w /workspace \
            eduardfomichev/test-runner:latest \
            python -m pytest tests

      - name: Store allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1

  generate-report:
      runs-on: ubuntu-latest
      needs: integration
      name: Generate report
      steps:
        - uses: actions/setup-java@v4
          with:
            distribution: 'microsoft'
            java-version: '17'
        - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.tgz && sudo tar -zxvf allure-2.30.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.30.0/bin/allure /usr/bin/allure
        - name: Download all workflow run artifacts
          uses: actions/download-artifact@v4
        - run: allure generate -c allure-results -o allure-report
        - name: Store generated report
          uses: actions/upload-artifact@v4
          with:
            name: allure-report
            path: allure-report
            retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
